"""
Django settings for alfateh project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""




import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", 'تقدر تخلي هنا نسخة سرية أكتر')

DEBUG = False

ALLOWED_HOSTS = ["fatihcenter.com", "www.fatihcenter.com", "127.0.0.1", "localhost","158.220.126.8"]  # عدّل الدومين حسب مشروعك

# PostgreSQL Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'afhath',
        'USER': 'ahmed',
        'PASSWORD': 'aahh01065830711',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Static/Media
STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/alfateh-static'


MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/alfateh-media'

# Apps
INSTALLED_APPS = [
    # ثالث الأطراف
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'djoser',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    
    'django.contrib.sites',
    # 'drf_yasg',
    'django_extensions',
    'social_django',

    # Django الأساسية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',

    # تطبيقاتك
    'api.apps.ApiConfig',
    'accounts.apps.AccountsConfig',
    'cores.apps.CoresConfig',
    
    'allauth',

'allauth.account',

'allauth.socialaccount',

'allauth.socialaccount.providers.google',

'allauth.socialaccount.providers.github',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
      "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'alfateh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alfateh.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Cairo'
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'social_core.backends.google.GoogleOAuth2',
]

# REST
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
}

# CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://158.220.126.8",
    "http://fatihcenter.com",
    "https://fatihcenter.com",
    "https://fatihcenter.com",
    "https://www.fatihcenter.com",
    "https://127.0.0.1",
     "http://127.0.0.1"

]
CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']
CORS_ALLOW_HEADERS = ['accept', 'authorization', 'content-type', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with']

X_FRAME_OPTIONS = 'ALLOWALL'

# البريد التجريبي
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# بيانات الإيميل بتاعك
EMAIL_HOST_USER = "support@fatihcenter.com"

EMAIL_HOST_PASSWORD = "your_app_password"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '15456467501-m42u5nmlbftglmsqpl4ijrl46c98fv7f.apps.googleusercontent.com',
            'secret':'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',
            'key': ''
        },
        'OAUTH_PKCE_ENABLED': True,
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'offline'},
        'REDIRECT_URI': 'https://fatihcenter.com/accounts/google/login/callback/'
    }
}


CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

LOGIN_REDIRECT_URL = '/'  # أو أي صفحة تريدها
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django. core.mail.backends. console. EmailBackend'
